version: '3'

volumes:
  certango_local_postgres_data: {}
  certango_local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: certango_local_django
    container_name: certango_local_django
    depends_on:
      - postgres
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    environment:
      - POSTGRES_HOST=postgres
    ports:
      - "8000:8000"

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: certango_production_postgres
    container_name: certango_local_postgres
    volumes:
      - certango_local_postgres_data:/var/lib/postgresql/data
      - certango_local_postgres_data_backups:/backups
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.local/.postgres
