name: CI

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

  push:
    branches: [ "master", "main" ]
    paths-ignore: [ "docs/**" ]

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "requirements/local.txt"

      - name: Install Deps
        run: pip install -r requirements/local.txt

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

  pytest:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL: "postgres://certango:certango@127.0.0.1/certango"
    steps:
      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Start Postgres
        run:  docker-compose -f local.yml up -d postgres

      - name: debug
        run: env && netstat -antp

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: pip
          cache-dependency-path: "requirements/local.txt"

      - name: Install Deps
        run: pip install -r requirements/local.txt

      - name: Run DB Migrations
        run:  python manage.py migrate

      - name: Run Django Tests
        run:  pytest

      - name: Tear down the Stack
        run:  docker-compose -f local.yml down

#  sonarcloud:
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#      with:
#        fetch-depth: 0
#
#    - name: Build the Stack
#      run:  docker-compose -f local.yml build
#
#    - name: Run Django Tests
#      run:  docker-compose -f local.yml run django
#
#    - name: SonarCloud Scan
#      uses: sonarsource/sonarcloud-github-action@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
